### ISSUE TITLE
Great Example - But Introduces timing issue with rendering logic

### ISSUE THREAD

**Issue by htmlsplash** [gragra33/BlazorDataConsumer#1]
In this example the menu contains the Data Source inside as follows:

-Menu open tag -
 -DataSource component -
-Menu Close tag-

GOAL:
The menu needs to render based on the data provided by the data source component.

PROBLEM;
Since the menu renders "before" the Data Source Component executes it has no data to render. Once the Data Source component has data the menu has already rendered. 

How do you solve this problem? I want the menu to render after the data-source control has supplied data but still retain the current tree/element structure.  Is this possible?

I have experimented by calling OnDataBound() when we have data bound and then in there re-invoking the rendering logic with StateHasChanged() but that causes infinite loop. Which makes sense because StateHasChanged on the menu control will re-render again its child content. Help is much appreciated.

**Comment by gragra33** [comment]
You need a state flag for your razor component/page where the menu is situated. For example:

```cs
private bool isLoaded;
```

Then, in your razor:

```cs
@if(isLoaded)
{
   // menu goes here
}
else
{
    // waiting for menu to be loaded
}
```

Then, when the menu is loaded:

```cs
isLoaded = true;
InvokeAsync(StateHasChanged);
```

**Comment by htmlsplash** [comment]
That will not work in my Menu control (I am not sure why I need to put this in the page, the Menu control renders blank because there's no data yet when it renders). As I mentioned, this will create an infinite loop.
The menu calling: InvokeAsync(StateHasChanged); will force re-render the menu which will re-render the SiteMapDataSource component, which will cause re-bind to data, which will cause OnDataBound() to be called again which will call again InvokeAsync(StateHasChanged); This will go in a circular loop.

This is the code from the Menu I have:

```
protected override void OnDataBound()
{
	_itemsQueue.Enqueue(this.RootItem);
	InvokeAsync(StateHasChanged);
}
```

**Comment by gragra33** [comment]
We had a storm here last night and our home has severe water damage. I'm writing to you from my mobile phone. Last night I ordered a new PC as my dev box went under water. As soon as I can get the new dev box delivered, and up and running, I will have a closer look.

**Comment by htmlsplash** [comment]
Oh dear ...., sorry to hear about this. I am glad you are okay though. Thanks.
As per my problem, I would like to add: It would be great if a Component could invalidate (force to re-render) only a portion of its region, instead of having the entire component to re-render and all its children. Let me know if that is possible currently in Blazor?

**Comment by htmlsplash** [comment]
I resolved my problem with this hackery:

```
@if (!_cascadingParametersSet)
{
	<CascadingValue Value="this">
		@ChildContent
	</CascadingValue>

	_cascadingParametersSet = true;
}
```

To be honest, not very proud of it but works. I wonder if there's a better solution?
Or ...
Maybe it is better to nest your component in a natural rendering order, so instead of:

-Menu open tag -
-DataSource component -
-Menu Close tag-

Order it this way:

-DataSource  open tag -
-Menu component -
-DataSource Close tag-

Is that the better recommendation and solution to the problem?

**Comment by gragra33** [comment]
@htmlsplash I've finally got my dev box set up and had a look at this. The `MenuComponent` already handles this. Here is the code:

```cs
@if (HasEntries)
{
    @foreach (SiteMapEntry entry in DataSource!)
    {
        <p>@entry.Title</p>
    }
}
else
{
    <div>No site map entries</div>
}
```

It handles the state correctly. I'm not sure what your code is and why you are having issues. I suggest it is an issue within your logic.

**Comment by htmlsplash** [comment]
Thanks for the update. I downloaded the code and ran it and it works as expected. The key piece of code that prevents recursion but yet renders the menu correctly with all the items (after data source is supplied) is this code:

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    // check on startup if we have data to show...
    if (firstRender)
        await UpdateSiteMapAsync();
}
```

After the menu renders for the first time, it is re-rendered again based on the supplied data source from the data provider. To prevent recursion the 2nd render phase doesn't cause a 3rd re-render because of checking the firstRender parameter.
